security:
#pattern
  pattern: /
#form login
  login-page: /signIn
  failure-url: /signIn?error=true
  username-parameter: username
  password-parameter: password
#logout
  invalidate-http-session: true
  clear-authentication: true
  logout-request-matcher: /logout
  logout-success-url: /
#session management
  invalid-session-url: /signIn
  maximum-sessions: 1
  expired-url: /signIn
#remember me
  remember-me-parameter: remember-me
  remember-me-cookie-name: remember_me_cookie
  token-validity-seconds: 86400
#authentication manager
  users-by-username-query: SELECT username, password, enabled FROM users WHERE username=?
  authorities-by-username-query: SELECT username, authorities FROM users WHERE username=?
#password encoder
  strength-password-encoder: 12


#reCaptcha
app.reCaptcha:
  apiUrl: https://www.google.com/recaptcha/api/siteverify
  secretKey: 6LeTEjAUAAAAAB23AV1aokKfDYhfP-HLIV90DRWq
