spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql:database
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 250
    connection-test-query: SELECT 1

eclipse-link:
  persistence-unit-name: unitPostgreSQL
  database-platform: org.eclipse.persistence.platform.database.PostgreSQLPlatform
  generate-dll: true
  show-sql: true
  weaving: static