#settings datasource
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql:database
  username: root
  password: root
  schema: classpath:/db/init/schema.sql

#settings hibernate
spring.jpa:
  hibernate.ddl-auto: update
  properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

#settings mail
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: TkM2Gs9Hrd@gmail.com
  password: 8pKZu9SStJ
  properties.mail.smtp:
    auth: true
    starttls.enable: true

#server
server:
  port: 8443
  session.timeout: 25200
  ssl:
    key-store: classpath:keystore/keyStore.jks
    key-store-password: JonkiPro
    key-password: JonkiPro
    key-alias: some_alias
    enabled: true

#security require SSL
security.require-ssl: true
security.basic.enabled: false

#messages
spring.messages:
  basename: internationalization/viewMessages,\
            internationalization/validationMessages,\
            static/linkToCssAndJs
  encoding: UTF-8
  cache-seconds: -1
  fallback-to-system-locale: true

#logging
logging.level.org.springframework.web: DEBUG

#Spring Profiles
spring:
  profiles:
    include: security
  application:
    name: REST-Web-Services

#banner
banner:
  location: banner.txt
